### ISSUE TITLE
Why abs_path()?

### ISSUE THREAD

**Issue by perlancar** [gflohr/libintl-perl#6]
In `__find_domain()` why is there a call to abs_path()? I don't think it's necessary. It adds overhead and possible failure modes.

**Comment by gflohr** [comment]
The path is used as an argument to `bindtextdomain()` a few lines below. Therefore it has to be absolute because the working directory may change.

But it is sufficient to call `abs_path()` only on a hit, not on every directory tried.  I have changed this in 8c2b356. Thanks for reporting!
